const list = [
    {
      id: 1,
      title: "The 5AM Club",
      author: "by Robin Sharma | 9 December 2018",
      price: 240,
      img: "https://m.media-amazon.com/images/I/618ZOX7UNNL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "The Greatest Self-Help Book",
      author: "by Vex King & Kaushal | 8 December 2022",
      price: 519,
      img: "https://m.media-amazon.com/images/I/31ARa6N9ngL._SY445_SX342_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Self help book Take a journey of self love",
      author: "by Sathi Khatun | 3 August 2023",
      price: 150,
      img: "https://m.media-amazon.com/images/I/41LSdnDtlOL._SY445_SX342_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Good Vibes,Good life",
      author: "by Vex King | 4 December 2019",
      price: 427,
      img: "https://m.media-amazon.com/images/I/31Koj6Q27PL._SY445_SX342_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "You Can",
      author: "by George Matthew Adams | 6 August 2020",
      price: 99,
      img: "https://m.media-amazon.com/images/I/41AnbvGOT3L._SY445_SX342_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "The power of your Subconscious Mind",
      author: "by Dr. Joseph Murphy | 1 February 2015",
      price: 99,
      img: "https://m.media-amazon.com/images/I/41wVYuZMNTL._SY445_SX342_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Learn, Don't Study ",
      author: "by Pramath Raj Sinha | 27 March 2023",
      price: 246,
      img: "https://m.media-amazon.com/images/I/61CNwt1cAPL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "How to stop worrying and Start Living",
      author: "by Dale Carnegie | 10 February 2022",
      price: 99,
      img: "https://m.media-amazon.com/images/I/417QQB7xWyL._SY445_SX342_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "The Mountain is you",
      author: "by Brianna wiest | 25 December 2023",
      price: 368,
      img: "https://m.media-amazon.com/images/I/41vEj2ijGtL._SY445_SX342_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "The courage to be disliked",
      author: "by Iciro Kishimi and Fumitake koga | 23 March 2018",
      price: 337,
      img: "https://m.media-amazon.com/images/I/71k7V0QvcdL._SY466_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Stop Overthinking",
      author: "by  Nick Trenton  | 28 February 2023",
      price: 126,
      img: "https://m.media-amazon.com/images/I/51mZRRzwRzL._SY445_SX342_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "How To Talk to anyone",
      author: "by Leil lowndes | 25 July 2014",
      price: 241,
      img: "https://m.media-amazon.com/images/I/41VC-6wmHsL._SY445_SX342_.jpg",
      amount: 1,
    },
  ];
  
  export default list;